version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: test1
    ports:
      - "3307:3306"
    volumes:
      - ./init:/docker-entrypoint-initdb.d 
    networks:
      - habit-net

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - habit-net

  backend:
    image: crpi-qbqc3mvo2gxrnwcm.cn-beijing.personal.cr.aliyuncs.com/habitbuilder/habitbuilder-back:latest
    container_name: backend
    depends_on:
      - mysql
      - redis
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/test1?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=123456
    networks:
      - habit-net

  frontend:
    image: crpi-qbqc3mvo2gxrnwcm.cn-beijing.personal.cr.aliyuncs.com/habitbuilder/habitbuilder-front:latest
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - habit-net

networks:
  habit-net:
    driver: bridge
